---
title: "Anderson-Rubin Confidence Intervals based on `feols` IV regression objects"
vignette: >
  %\VignetteIndexEntry{Anderson-Rubin Confidence Intervals based on `feols` IV regression objects}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---

In this vignette, we demonstrate how to compute Anderson-Rubin confidence intervals for instrumental variables regression models estimated using the `feols` function from the `fixest` package. The Anderson-Rubin method provides robust inference in the presence of weak instruments.

We will use the built-in `mtcars` dataset for illustration. In this example, we will regress `mpg` (miles per gallon) on `cyl` (number of cylinders) using `hp` (horsepower) as an endogenous regressor and `qsec` (1/4 mile time) as an instrument.

First, we run a regression using `feols`.

Second, we compute the Anderson-Rubin confidence intervals for the coefficient of the endogenous regressor `hp` using the `ar_ci` function from the `arci` package.

Then, we visualize the results and extract the confidence intervals using the `get_ar_ci` function.

Finally, we use `get_ar_ci` to extract the computed confidence intervals in a tidy format.

```{r}
#| label: setup
library(arci)
library(fixest)

regression <- feols(mpg ~ cyl | hp ~ qsec, data = mtcars)
etable(regression)

arci_results <- ar_ci(regression, param = "hp", level = 0.95)
print(arci_results)

plot(arci_results)

get_ar_ci(regression)
```
